favicon: /images/favicon.png

# Open Graph metadata (https://hexo.io/docs/helpers.html#open-graph)
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

article:
  readtime: true
  highlight: atom-one-light
  date_format: full_relative

menu:
  Blog: /
  About: /about

search:
  type: insight

toc: false

plugins:
  mathjax: false
  katex: false
  gallery: false
  clipboard: true
  google-analytics:
    tracking_id: G-82M11FYLK0

navbar_links:
  Spotify:
    icon: fab fa-spotify
    url: https://open.spotify.com/show/7vC4mEgUTKe7BJNzdHBvPo
  Apple Podcasts:
    icon: fa fa-podcast
    url: https://podcasts.apple.com/us/podcast/המייסדים/id1628004036
  Google Podcasts:
    icon: fab fa-google
    url: https://open.spotify.com/show/7vC4mEgUTKe7BJNzdHBvPo

